### ISSUE TITLE
Nothing Works On Startup

### ISSUE THREAD

**Issue by fennifith** [TheAndroidMaster/Blackboard#7]
This is a bit of a weird issue, might have something to do with the website loading a different page, but the app sometimes can't scrape any of the right info when it opens after being closed not long ago. Maybe the Application class is still active or something...

**Comment by fennifith** [comment]
Wait. I'm an idiot. The application class is still active.

**Comment by fennifith** [comment]
The WebView is in the application class.

**Comment by fennifith** [comment]
It doesn't load anything again. It keeps the page from the last time the app was opened.

**Comment by jaduprey** [comment]
So how do you resolve it?

**Comment by fennifith** [comment]
@jaduprey in the commit I made it reset the WebView when the app is started
